version: '2.3'

services:

# P0f service
  p0f:
    build: .
    container_name: p0f
    restart: always
#    cpu_count: 1
#    cpus: 0.75
    network_mode: "host"
    image: "4ss078/p0f"
    read_only: true
    volumes:
     - /data/p0f/log:/var/log/p0f
